/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.a3.Interfaces;

import com.mycompany.a3.daos.LotesDAO;
import com.mycompany.a3.daos.ProdutoDAO;
import com.mycompany.a3.models.Lote;
import com.mycompany.a3.models.LotePerecivel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class LotesTela extends javax.swing.JPanel {

    public LotesTela() {
        initComponents();
        LotesDAO lotesDAO = new LotesDAO();
        lotesDAO.marcarLotesInativos();
        List<Lote> lotes = lotesDAO.selectAll();
        preencheTableLotes(lotes);
    }

    private void preencheTableLotes(List<Lote> lotes) {
        if (lotes != null) {
            DefaultTableModel model = (DefaultTableModel) tableLotes.getModel();
            model.setRowCount(0);
            lotes.forEach(l -> {

                if ((l instanceof LotePerecivel)) {
                    LotePerecivel lotePerecivel = (LotePerecivel) l;
                    String bloqueado;
                    if (lotePerecivel.getBloqueado() == 0) {
                        bloqueado = "Não";

                    } else {
                        bloqueado = "Sim";
                    }

                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                    String dataBloqueioFormatada = "";
                    if (lotePerecivel.getDataBloqueio() != null && !lotePerecivel.getDataBloqueio().equals("") && bloqueado.equals("Sim")) {
                        formato.setLenient(false);
                        dataBloqueioFormatada = formato.format(lotePerecivel.getDataBloqueio());
                    }

                    String dataValidadeFormatada = "";
                    if (lotePerecivel.getValidade() != null && !lotePerecivel.getDataBloqueio().equals("")) {
                        dataValidadeFormatada = formato.format(lotePerecivel.getValidade());
                    }

                    Object[] linha = {l.getId(), l.getIdentificador(), l.getProduto(), l.getEstoque(), "Perecível", dataValidadeFormatada, bloqueado, dataBloqueioFormatada, ((LotePerecivel) l).getMotivoBloqueio()};
                    model.addRow(linha);

                } else {
                    Object[] linha = {l.getId(), l.getIdentificador(), l.getProduto(), l.getEstoque(), "Não Perecível"};
                    model.addRow(linha);
                }

            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloJanela = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLotes = new javax.swing.JTable();

        labelTituloJanela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTituloJanela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloJanela.setText("Lotes");

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tableLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Identificador", "Produto", "Estoque", "Tipo", "Validade", "Bloqueado", "Data do Bloqueio", "Motivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableLotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableLotes.setShowGrid(true);
        jScrollPane1.setViewportView(tableLotes);
        if (tableLotes.getColumnModel().getColumnCount() > 0) {
            tableLotes.getColumnModel().getColumn(0).setMaxWidth(50);
            tableLotes.getColumnModel().getColumn(1).setMaxWidth(200);
            tableLotes.getColumnModel().getColumn(2).setMinWidth(200);
            tableLotes.getColumnModel().getColumn(2).setMaxWidth(200);
            tableLotes.getColumnModel().getColumn(3).setMaxWidth(100);
            tableLotes.getColumnModel().getColumn(5).setMinWidth(100);
            tableLotes.getColumnModel().getColumn(5).setMaxWidth(100);
            tableLotes.getColumnModel().getColumn(6).setMinWidth(100);
            tableLotes.getColumnModel().getColumn(6).setMaxWidth(100);
            tableLotes.getColumnModel().getColumn(7).setMinWidth(100);
            tableLotes.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTituloJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloJanela)
                .addGap(3, 3, 3)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CadastroLoteTela cadastroLoteTela = new CadastroLoteTela();
        cadastroLoteTela.setVisible(true);

        cadastroLoteTela.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                LotesDAO lotesDAO = new LotesDAO();
                List<Lote> lotes = lotesDAO.selectAll();
                preencheTableLotes(lotes);
            }
        });
        ;
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloJanela;
    private javax.swing.JTable tableLotes;
    // End of variables declaration//GEN-END:variables
}
